apiVersion: apps/v1
kind: Deployment
metadata:
  name: greeter-server
  labels:
    app: greeter-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: greeter-server
  template:
    metadata:
      labels:
        app: greeter-server
        spire.spiffe.io/spiffeid: greeter-server
    spec:
      containers:
      - name: greeter-server
        image: greeter-server:demo
        imagePullPolicy: Never
        args: ["--addr", ":8443"]
        volumeMounts:
        - name: spire-agent-socket
          mountPath: /run/secrets/workload-spiffe-uds
          readOnly: true
        env:
        - name: SPIFFE_ENDPOINT_SOCKET
          value: unix:///run/secrets/workload-spiffe-uds/socket
      volumes:
      - name: spire-agent-socket
        csi:
          driver: "csi.spiffe.io"
          readOnly: true
