apiVersion: v1
kind: Service
metadata:
  name: spire-server
  namespace: spire
spec:
  type: NodePort
  ports:
    - name: grpc
      port: 8081
      targetPort: 8081
      protocol: TCP
    - name: bundle-api
      port: 8443
      targetPort: 8443
      nodePort: 30007
      protocol: TCP
  selector:
    app: spire-server
