apiVersion: spire.spiffe.io/v1alpha1
kind: ClusterSPIFFEID
metadata:
  name: greeter-client
spec:
  spiffeIDTemplate: "spiffe://google.com/ns/{{ .PodMeta.Namespace }}/sa/{{ .PodSpec.ServiceAccountName }}"
  podSelector:
    matchLabels:
      spire.spiffe.io/spiffeid: greeter-client
  federatesWith: ["aws.com"]
